### ISSUE TITLE
Use CodedInputStream.setSizeLimit() to increase the size limit

### ISSUE THREAD

**Issue by akiranmutnuru** [TWCable/grabbit#110]
i am getting Status FAILURE
Status for JobId [6110131353824602498] is :
{
    "endTime": "2016-06-15T11:55:17+0000",
    "exitStatus": {
        "exitCode": "FAILED",
        "exitDescription": "",
        "running": false
    },
    "jcrNodesWritten": 60600,
    "jobExecutionId": 6110131353824602498,
    "path": "/content/dam/www-abcd-com",
    "startTime": "2016-06-15T11:48:25+0000",
    "timeTaken": 412049
}

and ERROR log is as below:

15.06.2016 13:55:07.414 *ERROR* [172.28.221.201 [1465991707412] GET /grabbit/job/61101313538246024986110131353824602498.json HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable java.lang.NumberFormatException: For input string: "61101313538246024986110131353824602498"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:444)
        at java.lang.Long.valueOf(Long.java:540)
        at com.twcable.grabbit.servlets.GrabbitServlet.getJsonString(GrabbitServlet.groovy:120)
        at com.twcable.grabbit.servlets.GrabbitServlet.doGet(GrabbitServlet.groovy:83)
        at org.apache.sling.api.servlets.SlingSafeMethodsServlet.mayService(SlingSafeMethodsServlet.java:268)
        at org.apache.sling.api.servlets.SlingAllMethodsServlet.mayService(SlingAllMethodsServlet.java:139)
        at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:344)
        at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:375)
        at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:508)
        at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:45)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:64)
        at com.day.cq.wcm.core.impl.WCMDebugFilter.doFilter(WCMDebugFilter.java:133)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
        at com.day.cq.wcm.core.impl.WCMComponentFilter.filterRootInclude(WCMComponentFilter.java:356)
        at com.day.cq.wcm.core.impl.WCMComponentFilter.doFilter(WCMComponentFilter.java:168)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
        at com.day.cq.personalization.impl.TargetComponentFilter.doFilter(TargetComponentFilter.java:96)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
        at org.apache.sling.engine.impl.SlingRequestProcessorImpl.processComponent(SlingRequestProcessorImpl.java:254)
        at org.apache.sling.engine.impl.filter.RequestSlingFilterChain.render(RequestSlingFilterChain.java:49)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:64)
        at com.day.cq.wcm.core.impl.AuthoringUIModeServiceImpl.doFilter(AuthoringUIModeServiceImpl.java:301)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
        at com.day.cq.wcm.core.impl.warp.TimeWarpFilter.doFilter(TimeWarpFilter.java:106)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
        at com.day.cq.wcm.mobile.core.impl.redirect.RedirectFilter.doFilter(RedirectFilter.java:290)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
        at org.apache.sling.engine.impl.debug.RequestProgressTrackerLogFilter.doFilter(RequestProgressTrackerLogFilter.java:64)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
        at com.day.cq.wcm.foundation.forms.impl.FormsHandlingServlet.doFilter(FormsHandlingServlet.java:221)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
        at com.day.cq.theme.impl.ThemeResolverFilter.doFilter(ThemeResolverFilter.java:76)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
        at com.adobe.granite.optout.impl.OptOutFilter.doFilter(OptOutFilter.java:74)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
        at com.day.cq.wcm.core.impl.WCMRequestFilter.doFilter(WCMRequestFilter.java:90)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
        at com.day.cq.wcm.designimporter.CanvasPageDeleteRequestFilter.doFilter(CanvasPageDeleteRequestFilter.java:88)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
        at org.apache.sling.rewriter.impl.RewriterFilter.doFilter(RewriterFilter.java:83)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
        at com.upc.filter.AbstractHtmlOutputFilter.doFilter(AbstractHtmlOutputFilter.java:49)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
        at com.lgi.globalvariables.servlets.FilterPageWithGlobalVariables.doFilter(FilterPageWithGlobalVariables.java:70)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
        at com.upc.filter.AbstractHtmlOutputFilter.doFilter(AbstractHtmlOutputFilter.java:49)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
        at com.upc.filter.AbstractHtmlOutputFilter.doFilter(AbstractHtmlOutputFilter.java:49)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
        at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:127)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
        at com.upc.filter.AbstractHtmlOutputFilter.doFilter(AbstractHtmlOutputFilter.java:52)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
        at org.apache.sling.bgservlets.impl.BackgroundServletStarterFilter.doFilter(BackgroundServletStarterFilter.java:135)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
        at org.apache.sling.engine.impl.SlingRequestProcessorImpl.processRequest(SlingRequestProcessorImpl.java:151)
        at org.apache.sling.engine.impl.SlingMainServlet.service(SlingMainServlet.java:206)
        at org.apache.felix.http.base.internal.handler.ServletHandler.doHandle(ServletHandler.java:96)
        at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:79)
        at org.apache.felix.http.base.internal.dispatch.ServletPipeline.handle(ServletPipeline.java:42)
        at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:49)
        at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:33)
        at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:127)
        at org.apache.felix.http.base.internal.handler.FilterHandler.doHandle(FilterHandler.java:88)
        at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:76)
        at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:47)
        at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:33)
        at com.adobe.granite.license.impl.LicenseCheckFilter.doFilter(LicenseCheckFilter.java:179)
        at org.apache.felix.http.base.internal.handler.FilterHandler.doHandle(FilterHandler.java:88)
        at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:76)
        at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:47)
        at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:33)
        at org.apache.felix.http.sslfilter.internal.SslFilter.doFilter(SslFilter.java:55)
        at org.apache.felix.http.base.internal.handler.FilterHandler.doHandle(FilterHandler.java:88)
        at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:76)
        at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:47)
        at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:33)
        at org.apache.sling.security.impl.ReferrerFilter.doFilter(ReferrerFilter.java:263)
        at org.apache.felix.http.base.internal.handler.FilterHandler.doHandle(FilterHandler.java:88)
        at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:76)
        at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:47)
        at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:33)
        at org.apache.sling.engine.impl.log.RequestLoggerFilter.doFilter(RequestLoggerFilter.java:75)
        at org.apache.felix.http.base.internal.handler.FilterHandler.doHandle(FilterHandler.java:88)
        at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:76)
        at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:47)
        at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:33)
        at org.apache.felix.http.base.internal.dispatch.FilterPipeline.dispatch(FilterPipeline.java:48)
        at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:39)
        at org.apache.felix.http.base.internal.DispatcherServlet.service(DispatcherServlet.java:67)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at com.day.j2ee.servletengine.ServletRuntimeEnvironment.service(ServletRuntimeEnvironment.java:250)
        at com.day.j2ee.servletengine.RequestDispatcherImpl.doFilter(RequestDispatcherImpl.java:321)
        at com.day.j2ee.servletengine.RequestDispatcherImpl.service(RequestDispatcherImpl.java:340)
        at com.day.j2ee.servletengine.RequestDispatcherImpl.service(RequestDispatcherImpl.java:383)
        at com.day.j2ee.servletengine.ServletHandlerImpl.process(ServletHandlerImpl.java:335)
        at com.day.j2ee.servletengine.HttpListener$Worker.run(HttpListener.java:644)
        at java.lang.Thread.run(Thread.java:745)
15.06.2016 13:55:07.415 *WARN* [172.28.221.201 [1465991707412] GET /grabbit/job/61101313538246024986110131353824602498.json HTTP/1.1] com.upc.util.Portal Not accessing a portal
15.06.2016 13:55:17.546 *ERROR* [clientJobLauncherTaskExecutor-1] org.springframework.batch.core.step.AbstractStep Encountered an error executing step clientJcrNodes in job clientJob com.google.protobuf.InvalidProtocolBufferException: Protocol message was too large.  May be malicious.  Use CodedInputStream.setSizeLimit() to increase the size limit.
        at com.google.protobuf.InvalidProtocolBufferException.sizeLimitExceeded(InvalidProtocolBufferException.java:89)
        at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:720)
        at com.google.protobuf.CodedInputStream.isAtEnd(CodedInputStream.java:666)
        at com.google.protobuf.CodedInputStream.readTag(CodedInputStream.java:99)
        at com.twcable.grabbit.proto.NodeProtos$Properties$Builder.mergeFrom(NodeProtos.java:1177)
        at com.twcable.grabbit.proto.NodeProtos$Properties$Builder.mergeFrom(NodeProtos.java:1029)
        at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:275)
        at com.twcable.grabbit.proto.NodeProtos$Node$Builder.mergeFrom(NodeProtos.java:499)
        at com.twcable.grabbit.proto.NodeProtos$Node$Builder.mergeFrom(NodeProtos.java:285)
        at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:275)
        at com.twcable.grabbit.proto.NodeProtos$Node$Builder.mergeFrom(NodeProtos.java:505)
        at com.twcable.grabbit.proto.NodeProtos$Node$Builder.mergeFrom(NodeProtos.java:285)
        at com.google.protobuf.AbstractMessageLite$Builder.mergeFrom(AbstractMessageLite.java:212)
        at com.google.protobuf.AbstractMessage$Builder.mergeFrom(AbstractMessage.java:746)
        at com.google.protobuf.AbstractMessage$Builder.mergeFrom(AbstractMessage.java:238)
        at com.google.protobuf.AbstractMessageLite$Builder.mergeDelimitedFrom(AbstractMessageLite.java:282)
        at com.google.protobuf.AbstractMessage$Builder.mergeDelimitedFrom(AbstractMessage.java:760)
        at com.google.protobuf.AbstractMessageLite$Builder.mergeDelimitedFrom(AbstractMessageLite.java:288)
        at com.google.protobuf.AbstractMessage$Builder.mergeDelimitedFrom(AbstractMessage.java:752)
        at com.twcable.grabbit.proto.NodeProtos$Node.parseDelimitedFrom(NodeProtos.java:242)
        at com.twcable.grabbit.client.batch.steps.jcrnodes.JcrNodesReader.read(JcrNodesReader.groovy:40)
        at com.twcable.grabbit.client.batch.steps.jcrnodes.JcrNodesReader.read(JcrNodesReader.groovy)
        at org.springframework.batch.core.step.item.SimpleChunkProvider.doRead(SimpleChunkProvider.java:91)
        at org.springframework.batch.core.step.item.SimpleChunkProvider.read(SimpleChunkProvider.java:155)
        at org.springframework.batch.core.step.item.SimpleChunkProvider$1.doInIteration(SimpleChunkProvider.java:114)
        at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368)
        at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
        at org.springframework.batch.repeat.support.RepeatTemplate.iterate(Repea
        at org.springframework.batch.core.step.item.SimpleChunkProvider.provide(
        at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransact
        at org.springframework.transaction.support.TransactionTemplate.execute(T
        at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkCo
        at org.springframework.batch.core.scope.context.StepContextRepeatCallbac
        at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult
        at org.springframework.batch.repeat.support.RepeatTemplate.executeIntern
        at org.springframework.batch.repeat.support.RepeatTemplate.iterate(Repea
        at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(Tas
        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep
        at org.springframework.batch.core.job.SimpleStepHandler.handleStep(Simpl
        at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(J
        at org.springframework.batch.core.job.flow.support.state.StepState.handl
        at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(Sim
        at org.springframework.batch.core.job.flow.support.SimpleFlow.start(Simp
        at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.jav
        at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.ja
        at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
        at java.lang.Thread.run(Thread.java:745)
15.06.2016 13:55:49.952 *WARN* [172.28.221.201 [1465991749950] GET /grabbit/job/6110131353824602498.json HTTP/1.1] com.twcable.grabbit.resources.GrabbitResourceProvider Unable to find resource for path: /grabbit.

i have executed the same path three times and FAILED all three times
but through installation of the package, it was successful

**Comment by jdigger** [comment]
For job "6110131353824602498" for some reason it's saying that it's receiving a request for job "61101313538246024986110131353824602498" (in other words, the number concatenated with itself twice), which is why it won't parse to a `long`.

How are you invoking that URL? With [grabbit.sh](https://github.com/TWCable/grabbit/blob/master/grabbit.sh)?

**Comment by jbornemann** [comment]
I see you are synching DAM content. 

```
15.06.2016 13:55:17.546 ERROR [clientJobLauncherTaskExecutor-1] org.springframework.batch.core.step.AbstractStep Encountered an error executing step clientJcrNodes in job clientJob com.google.protobuf.InvalidProtocolBufferException: Protocol message was too large. May be malicious. Use CodedInputStream.setSizeLimit() to increase the size limit.
```

Here tells me that we may be exceeding the default 64MB buffer limit.  This has been recorded here: https://github.com/TWCable/grabbit/issues/2 as well. We should definitely look into a way of handling this, if either by providing our own "preloaded buffer" as is an example in #2, or rethinking how we sync DAM content entirely.

**Comment by akiranmutnuru** [comment]
I AM USING GRABBIT 3.0.5 VERSION FOR AEM 5.6
IS IT POSSIBLE TO MAKE IT ENHANCED WITH THIS FEATURE??

**Comment by akiranmutnuru** [comment]
Is there any workaround for this issue?

**Comment by jbornemann** [comment]
There isn't a great workaround. You can partition off large DAM assets (over 64MB) to a different part of the tree, manage the rest through Grabbit, and manage the large assets another way. 

Of course, PR submissions are always welcome :-)

**Comment by akiranmutnuru** [comment]
I am trying to fetch the DAM assets by filter with its size as below  but this query is not working 

SELECT * from [dam:Asset] as a WHERE a.[jcr:content/metadata/dam:size] > 5403

error is :
'/' not allowed in name

Please help me
Thanks a million:)

**Comment by viveksachdeva** [comment]
@akiranmutnuru : I tried the same query in SQL and SQL2 both.. it works alright for me...

**Comment by akiranmutnuru** [comment]
great!
i tried in different ways but no luck!
is there any syntax error in my query?
can you please share yours?

FYI: I am using CQ5.6

**Comment by jbornemann** [comment]
@akiranmutnuru I don't have a 5.6 instance on me at the moment, but try  :  
```
SELECT * from [dam:Asset] as asset WHERE asset."jcr:content/metadata/dam:size" > 5403
```

**Comment by akiranmutnuru** [comment]
NO. still not working
same result as below:
'/' not allowed in name

**Comment by viveksachdeva** [comment]
@akiranmutnuru : I can now see your issue... I think it started working with introduction of oak.. I noticed one more thing on 5.6 DAM.. I cannot seem to find dam:size in the metadata properties.. So though I could query other properties alright using query debugger(http://localhost:4502/libs/cq/search/content/querydebug.html) but nothing for damSize as it does not exist.. here is the query that I used. May be helpful:
`
type=dam:Asset
property=jcr:content/metadata/dam:MIMEtype
property.value=image/jpeg
`

**Comment by akiranmutnuru** [comment]
i am using VLT for all DAM assets instead of querying for the larger assets. May be that is better for now till the issue got resolved in Grabbit tool

**Comment by jdigger** [comment]
Closing in favor of prioritizing GH-2.
