### ISSUE TITLE
javax.jcr.nodetype.ConstraintViolationException

### ISSUE THREAD

**Issue by akiranmutnuru** [TWCable/grabbit#116]
i am trying to copy the path
/etc/stepplan

I got below error 
screenshot attached
please help me why is the happening???????

Error message:
29.06.2016 13:21:48.902 *ERROR* [clientJobLauncherTaskExecutor-10] org.springframework.batch.core.step.AbstractStep Encountered an error executing step clientJcrNodes in job clientJob javax.jcr.nodetype.ConstraintViolationException: no matching property definition found for {http://www.jcp.org/jcr/1.0}title
        at org.apache.jackrabbit.core.nodetype.EffectiveNodeType.getApplicablePropertyDef(EffectiveNodeType.java:782)
        at org.apache.jackrabbit.core.NodeImpl.getApplicablePropertyDefinition(NodeImpl.java:842)
        at org.apache.jackrabbit.core.NodeImpl.getOrCreateProperty(NodeImpl.java:436)
        at org.apache.jackrabbit.core.NodeImpl$SetPropertyOperation.perform(NodeImpl.java:2051)
        at org.apache.jackrabbit.core.NodeImpl$SetPropertyOperation.perform(NodeImpl.java:1998)
        at org.apache.jackrabbit.core.session.SessionState.perform(SessionState.java:216)
        at org.apache.jackrabbit.core.NodeImpl.setProperty(NodeImpl.java:1913)
        at com.twcable.grabbit.jcr.ProtoPropertyDecorator.writeToNode(ProtoPropertyDecorator.groovy:54)
        at com.twcable.grabbit.jcr.ProtoNodeDecorator$_writeToJcr_closure5.doCall(ProtoNodeDecorator.groovy:72)
        at com.twcable.grabbit.jcr.ProtoNodeDecorator$_writeToJcr_closure5.call(ProtoNodeDecorator.groovy)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1379)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1372)
        at com.twcable.grabbit.jcr.ProtoNodeDecorator.writeToJcr(ProtoNodeDecorator.groovy:72)
        at com.twcable.grabbit.client.batch.steps.jcrnodes.JcrNodesWriter.writeToJcr(JcrNodesWriter.groovy:91)
        at com.twcable.grabbit.client.batch.steps.jcrnodes.JcrNodesWriter.write(JcrNodesWriter.groovy:74)
        at org.springframework.batch.core.step.item.SimpleChunkProcessor.writeItems(SimpleChunkProcessor.java:175)
        at org.springframework.batch.core.step.item.SimpleChunkProcessor.doWrite(SimpleChunkProcessor.java:151)
        at org.springframework.batch.core.step.item.SimpleChunkProcessor.write(SimpleChunkProcessor.java:274)
        at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:199)
        at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:75)
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:395)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
        at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:267)
        at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:77)
        at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368)
        at 
![nodes_structure](https://cloud.githubusercontent.com/assets/16877068/16450556/433bd150-3e1b-11e6-8006-01b3dd798155.png)
org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
        at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
        at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:253)
        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:195)
        at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:141)
        at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:64)
        at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:60)
        at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:151)
        at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:130)
        at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:135)
        at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:301)
        at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:134)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by jbornemann** [comment]
Hi @akiranmutnuru are both your client, and server machines running v3.0.5 on CQ5.6? If so, is it possible for us to get a content package with the offending node? What is the output of /crx/de/exportnodetype.jsp on the client, and server machines?

**Comment by jbornemann** [comment]
Grabbit 3.0.5 syncs namespaces between the servers, as well as enforces mandatory node structures; However, it can't, and won't settle discrepancies between definitions within the same namespace - As may be the case if you are synching between different versions of AEM.

**Comment by jdigger** [comment]
@akiranmutnuru Did Jeff's questions and explanation make sense?

**Comment by akiranmutnuru** [comment]
yes yes.
Apologies for the delay in response
but, I am not authorized to share information due to security issues

**Comment by jdigger** [comment]
@akiranmutnuru Did looking at `/crx/de/exportnodetype.jsp` on both machines clarify the issue?
