### ISSUE TITLE
Bundle does not start on AEM 6.2

### ISSUE THREAD

**Issue by thedoc31** [TWCable/grabbit#138]
Attempting to install Grabbit-6.0.0 on AEM 6.2, but the bundle throws error [1].  Hotfixes 10962, 11700, and 11490 are installed as well as the prereq Sun-Misc-Fragment-Bundle-1.0.0.zip. I do not see an org.joda.time bundle in /system/console/bundles.

[1]
10.08.2016 18:23:15.314 *ERROR* [qtp1594938978-7323] org.apache.felix.http.jetty %bundles.pluginTitle: Cannot start (org.osgi.framework.BundleException: Unable to resolve com.twcable.grabbit [475](R 475.0): missing requirement [com.twcable.grabbit [475](R 475.0)] osgi.wiring.package; (&(osgi.wiring.package=org.joda.time)(version>=1.6.0)(!(version>=2.0.0))) Unresolved requirements: [[com.twcable.grabbit [475](R 475.0)] osgi.wiring.package; (&(osgi.wiring.package=org.joda.time)(version>=1.6.0)(!(version>=2.0.0)))])
org.osgi.framework.BundleException: Unable to resolve com.twcable.grabbit [475](R 475.0): missing requirement [com.twcable.grabbit [475](R 475.0)] osgi.wiring.package; (&(osgi.wiring.package=org.joda.time)(version>=1.6.0)(!(version>=2.0.0))) Unresolved requirements: [[com.twcable.grabbit [475](R 475.0)] osgi.wiring.package; (&(osgi.wiring.package=org.joda.time)(version>=1.6.0)(!(version>=2.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
	at org.apache.felix.webconsole.internal.core.BundlesServlet.doPost(BundlesServlet.java:365)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.felix.webconsole.internal.servlet.OsgiManager.service(OsgiManager.java:567)
	at org.apache.felix.webconsole.internal.servlet.OsgiManager$3.run(OsgiManager.java:465)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.felix.webconsole.internal.servlet.OsgiManager.service(OsgiManager.java:461)
	at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:85)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:79)
	at com.adobe.granite.license.impl.LicenseCheckFilter.doFilter(LicenseCheckFilter.java:308)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at org.apache.felix.http.sslfilter.internal.SslFilter.doFilter(SslFilter.java:89)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at org.apache.sling.security.impl.ReferrerFilter.doFilter(ReferrerFilter.java:290)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:129)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at org.apache.sling.featureflags.impl.FeatureManager.doFilter(FeatureManager.java:116)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at org.apache.sling.engine.impl.log.RequestLoggerFilter.doFilter(RequestLoggerFilter.java:75)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:124)
	at org.apache.felix.http.base.internal.DispatcherServlet.service(DispatcherServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sagarsane** [comment]
Hi @thedoc31,

It appears that the way Joda Time was provided in AEM has changed in AEM 6.2

Here's what `org.joda.time` shows in `/system/console/depfinder` in AEM 6.1 : 

![aem61-jodatime-depfinder](https://cloud.githubusercontent.com/assets/667114/17578487/4b235656-5f57-11e6-8aec-4e8218aa8f6d.jpg)

And here's what `org.joda.time` shows in `/system/console/depfinder` in AEM 6.2 : 

![aem62-jodatime-depfinder](https://cloud.githubusercontent.com/assets/667114/17578494/6468b0fc-5f57-11e6-9026-a6dd20fe247d.jpg)

Grabbit is importing `org.joda.time; version="[1.6, 2)"` as seen in its MANIFEST.MF. Since version `1.6` doesn't exist in AEM 6.2 anymore, the bundle is not finding it... and thus failing to start.

It looks like this will need a dependency upgrade (for Grabbit to now depend on Joda-Time v2.9.1) for Grabbit for it to be compatible to AEM 6.2.

**Comment by sagarsane** [comment]
I've logged Issue #139 to track the work for this. Thanks for reporting!

**Comment by sagarsane** [comment]
Fixed by #140 

Grabbit 7.0.0 has been released on Bintray which has a fix for this issue among other things. https://github.com/TWCable/grabbit/releases/tag/v7.0.0

Please let us know if you have any issues with it!

**Comment by thedoc31** [comment]
Great thank you! I see that AEM 6.1 -> 6.2 was tested, but has AEM 6.0 -> 6.2 been tested? That's the scenario I'm faced with.
