### ISSUE TITLE
Exception writing JCR Nodes to current JCR Session

### ISSUE THREAD

**Issue by ksra1** [TWCable/grabbit#150]
I am trying to setup grabbit on my local AEM 6.0 instance (author & publish). Installed "grabbit-3.0.0.zip" and "Sun-Misc-Fragment-Bundle-1.0.0.zip". Seeing the following error when copying content from author(server) to publish(client). Any thoughts?
```
06.09.2016 17:01:09.194 *ERROR* [clientJobLauncherTaskExecutor-4] com.twcable.grabbit.client.batch.steps.jcrnodes.JcrNodesWriter Exception writing JCR Nodes to current JCR Session : session-1229. 
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:134)
	at org.apache.jackrabbit.oak.plugins.value.ValueImpl.getBlob(ValueImpl.java:45)
	at org.apache.jackrabbit.oak.plugins.memory.BinaryPropertyState.binaryProperty(BinaryPropertyState.java:82)
	at org.apache.jackrabbit.oak.plugins.memory.PropertyStates.createProperty(PropertyStates.java:62)
	at org.apache.jackrabbit.oak.jcr.session.ItemImpl.createSingleState(ItemImpl.java:371)
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl.internalSetProperty(NodeImpl.java:1292)
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl.setProperty(NodeImpl.java:356)
	at com.twcable.grabbit.jcr.ProtoPropertyDecorator.writeToNode(ProtoPropertyDecorator.groovy:54)
	at com.twcable.grabbit.jcr.ProtoNodeDecorator$_writeToJcr_closure5.doCall(ProtoNodeDecorator.groovy:72)
	at com.twcable.grabbit.jcr.ProtoNodeDecorator$_writeToJcr_closure5.call(ProtoNodeDecorator.groovy)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1379)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1372)
	at com.twcable.grabbit.jcr.ProtoNodeDecorator.writeToJcr(ProtoNodeDecorator.groovy:72)
	at com.twcable.grabbit.client.batch.steps.jcrnodes.JcrNodesWriter.writeToJcr(JcrNodesWriter.groovy:88)
	at com.twcable.grabbit.client.batch.steps.jcrnodes.JcrNodesWriter.writeToJcr(JcrNodesWriter.groovy:93)
	at com.twcable.grabbit.client.batch.steps.jcrnodes.JcrNodesWriter.write(JcrNodesWriter.groovy:71)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.writeItems(SimpleChunkProcessor.java:175)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.doWrite(SimpleChunkProcessor.java:151)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.write(SimpleChunkProcessor.java:274)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:199)
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:75)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:395)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:267)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:77)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:253)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:195)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:141)
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:64)
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:60)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:151)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:130)
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:135)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:301)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
06.09.2016 17:01:09.195 *ERROR* [clientJobLauncherTaskExecutor-4] org.springframework.batch.core.step.AbstractStep Encountered an error executing step clientJcrNodes in job clientJob
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:134)
	at org.apache.jackrabbit.oak.plugins.value.ValueImpl.getBlob(ValueImpl.java:45)
	at org.apache.jackrabbit.oak.plugins.memory.BinaryPropertyState.binaryProperty(BinaryPropertyState.java:82)
	at org.apache.jackrabbit.oak.plugins.memory.PropertyStates.createProperty(PropertyStates.java:62)
	at org.apache.jackrabbit.oak.jcr.session.ItemImpl.createSingleState(ItemImpl.java:371)
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl.internalSetProperty(NodeImpl.java:1292)
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl.setProperty(NodeImpl.java:356)
	at com.twcable.grabbit.jcr.ProtoPropertyDecorator.writeToNode(ProtoPropertyDecorator.groovy:54)
	at com.twcable.grabbit.jcr.ProtoNodeDecorator$_writeToJcr_closure5.doCall(ProtoNodeDecorator.groovy:72)
	at com.twcable.grabbit.jcr.ProtoNodeDecorator$_writeToJcr_closure5.call(ProtoNodeDecorator.groovy)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1379)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1372)
	at com.twcable.grabbit.jcr.ProtoNodeDecorator.writeToJcr(ProtoNodeDecorator.groovy:72)
	at com.twcable.grabbit.client.batch.steps.jcrnodes.JcrNodesWriter.writeToJcr(JcrNodesWriter.groovy:88)
	at com.twcable.grabbit.client.batch.steps.jcrnodes.JcrNodesWriter.writeToJcr(JcrNodesWriter.groovy:93)
	at com.twcable.grabbit.client.batch.steps.jcrnodes.JcrNodesWriter.write(JcrNodesWriter.groovy:71)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.writeItems(SimpleChunkProcessor.java:175)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.doWrite(SimpleChunkProcessor.java:151)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.write(SimpleChunkProcessor.java:274)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:199)
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:75)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:395)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:267)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:77)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:253)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:195)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:141)
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:64)
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:60)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:151)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:130)
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:135)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:301)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
06.09.2016 17:01:09.195 *INFO* [clientJobLauncherTaskExecutor-4] com.twcable.grabbit.client.batch.steps.jcrnodes.JcrNodesStepExecutionListener JcrNodes Step Complete. Current Path : /content/dam/geometrixx . Total nodes written : 0
```

**Comment by jbornemann** [comment]
Hey @ksra1, were you able to narrow down the error to an offending node? It seems like it is breaking within the Jackrabbit layer, possibly due to a malformed binary property. If you can get an example offending node, we can look into seeing if a fix is prudent on our end.

**Comment by ksra1** [comment]
Hi @jbornemann, Thanks for your response and sorry for not updating the issue. Turns out the problem is with the version I am using. Thanks for checking.
