### ISSUE TITLE
7.02: Received a status of 500 when attempting to create a connection

### ISSUE THREAD

**Issue by mfitch** [TWCable/grabbit#165]
When I run 7.02 in AEM 6.1 host to AEM 6.2(SP1) client I am able to push content without an issue.
I then try to push from AEM 6.2(Sp1) that just received the content to a AEM 6.2(SP1)  instance and I'm getting that error.

Here is what I am seeing on the source AEM (6.2 SP1) server that was able to receive content earlier.

29.12.2016 11:30:16.953 *ERROR* [10.8.131.237 [1483039816943] GET /grabbit/content HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable
java.lang.UnsupportedOperationException: Deserialization not allowed for class org.springframework.batch.core.JobExecution (on Thu Dec 29 11:30:16 PST 2016)
        at org.kantega.notsoserial.DefaultNotSoSerial.preventDeserialization(DefaultNotSoSerial.java:256)
...

This is on the client (AEM 6.2/SP1) that does not have any previous success 

29.12.2016 11:30:16.366 *INFO* [10.8.131.156 [1483039816073] PUT /grabbit/job HTTP/1.1] com.twcable.grabbit.client.batch.ClientBatchJob Kicked off job with ID : 6345700954439571595
29.12.2016 11:30:16.403 *DEBUG* [clientJobLauncherTaskExecutor-4] com.twcable.grabbit.client.batch.ClientBatchJobExecutionListener SlingRepository : com.adobe.granite.repository.impl.SlingRepositoryImpl@385f0262
29.12.2016 11:30:16.407 *INFO* [clientJobLauncherTaskExecutor-4] com.twcable.grabbit.client.batch.ClientBatchJobExecutionListener Starting job : JobExecution: id=6345700954439571595, version=1, startTime=Thu Dec 29 11:30:16 PST 2016, endTime=null, lastUpdated=Thu Dec 29 11:30:16 PST 2016, status=STARTED, exitStatus=exitCode=UNKNOWN;exitDescription=, job=[JobInstance: id=10, version=0, Job=[clientJob]], jobParameters=[{serverPassword=x, deleteBeforeWrite=true, scheme=http, port=4502, transactionID=6827577105229367456, clientUsername=admin, excludePaths=/content/kporg/en/hawaii/provider*/content/kporg/en/georgia/clinicians*/content/kporg/en/southern-colorado/clinicians*/content/kporg/en/southern-california/physicians*/content/kporg/en/oregon-washington/clinicians*/content/kporg/en/northern-california/physicians*/content/kporg/en/colorado-denver-boulder-mountain-northern/clinicians*/content/kporg/es/hawaii/provider*/content/kporg/es/georgia/clinicians*/content/kporg/es/southern-colorado/clinicians*/content/kporg/es/southern-california/physicians*/content/kporg/es/oregon-washington/clinicians*/content/kporg/es/northern-california/physicians*/content/kporg/es/colorado-denver-boulder-mountain-northern/clinicians, workflowConfigIds=, batchSize=1500, timestamp=1483039816327, serverUsername=admin, host=xjzxdea0400x.dta.kp.org, pathDeltaContent=false, path=/content/kporg}]

29.12.2016 11:30:16.407 *DEBUG* [clientJobLauncherTaskExecutor-4] com.twcable.grabbit.client.batch.steps.validation.ValidJobDecider com.twcable.grabbit.client.batch.steps.validation.ValidJobDecider Job determined to be valid for job path /content/kporg
29.12.2016 11:30:16.460 *INFO* [clientJobLauncherTaskExecutor-4] com.twcable.grabbit.client.batch.steps.workflows.WorkflowOffTasklet WorkflowConfig : 
29.12.2016 11:30:16.460 *INFO* [clientJobLauncherTaskExecutor-4] com.twcable.grabbit.client.batch.steps.workflows.WorkflowOffTasklet Nothing to process...
29.12.2016 11:30:16.519 *INFO* [clientJobLauncherTaskExecutor-4] com.twcable.grabbit.client.batch.steps.workspace.DeleteBeforeWriteDecider Will delete nodes under job path before writing for 6345700954439571595...
29.12.2016 11:30:16.557 *WARN* [clientJobLauncherTaskExecutor-3] com.twcable.grabbit.client.batch.steps.workspace.DeleteBeforeWriteTasklet deleteBeforeWrite was enabled for jobPath /content/dam/kporg but job path does not exist on client!
29.12.2016 11:30:16.729 *WARN* [clientJobLauncherTaskExecutor-4] com.twcable.grabbit.client.batch.steps.workspace.DeleteBeforeWriteTasklet deleteBeforeWrite was enabled for jobPath /content/kporg but job path does not exist on client!
29.12.2016 11:30:16.921 *WARN* [clientJobLauncherTaskExecutor-3] com.twcable.grabbit.client.batch.steps.http.CreateHttpConnectionTasklet Received a status of 500 when attempting to create a connection to xjzxdea0400x.dta.kp.org. Bailing out. See debug log for more details.

**I think this is the start of the error?**

29.12.2016 11:30:16.921 *DEBUG* [clientJobLauncherTaskExecutor-3] com.twcable.grabbit.client.batch.steps.http.CreateHttpConnectionTasklet Request to start a connection ## *# *with xjzxdea0400x.dta.kp.org resulted in: org.apache.http.conn.BasicManagedEntity@541ec0b8.**
29.12.2016 11:30:16.959 *WARN* [clientJobLauncherTaskExecutor-4] com.twcable.grabbit.client.batch.steps.http.CreateHttpConnectionTasklet Received a status of 500 when attempting to create a connection to xjzxdea0400x.dta.kp.org. Bailing out. See debug log for more details.

29.12.2016 11:30:16.959 *DEBUG* [clientJobLauncherTaskExecutor-4] com.twcable.grabbit.client.batch.steps.http.CreateHttpConnectionTasklet Request to start a connection with xjzxdea0400x.dta.kp.org resulted in: org.apache.http.conn.BasicManagedEntity@5c926e26.
29.12.2016 11:30:16.980 *INFO* [clientJobLauncherTaskExecutor-3] com.twcable.grabbit.client.batch.ClientBatchJobExecutionListener Cleanup : JobExecution: id=5273847000036560410, version=1, startTime=Thu Dec 29 11:30:16 PST 2016, endTime=Thu Dec 29 11:30:16 PST 2016, lastUpdated=Thu Dec 29 11:30:16 PST 2016, status=FAILED, exitStatus=exitCode=FAILED;exitDescription=, job=[JobInstance: id=9, version=0, Job=[clientJob]], jobParameters=[{serverPassword=x, deleteBeforeWrite=true, scheme=http, port=4502, transactionID=6827577105229367456, clientUsername=admin, excludePaths=, workflowConfigIds=, batchSize=300, timestamp=1483039816145, serverUsername=admin, host=xjzxdea0400x.dta.kp.org, pathDeltaContent=false, path=/content/dam/kporg}] . Job Complete. Releasing session, and input stream
29.12.2016 11:30:16.981 *INFO* [clientJobLauncherTaskExecutor-3] com.twcable.grabbit.client.batch.ClientBatchJobExecutionListener Grab from xjzxdea0400x.dta.kp.org for Current Path /content/dam/kporg took : 791 milliseconds

29.12.2016 11:30:17.020 *INFO* [clientJobLauncherTaskExecutor-4] com.twcable.grabbit.client.batch.ClientBatchJobExecutionListener Cleanup : JobExecution: id=6345700954439571595, version=1, startTime=Thu Dec 29 11:30:16 PST 2016, endTime=Thu Dec 29 11:30:17 PST 2016, lastUpdated=Thu Dec 29 11:30:16 PST 2016, status=FAILED, exitStatus=exitCode=FAILED;exitDescription=, job=[JobInstance: id=10, version=0, Job=[clientJob]], jobParameters=[{serverPassword=x, deleteBeforeWrite=true, scheme=http, port=4502, transactionID=6827577105229367456, clientUsername=admin

**Comment by jbornemann** [comment]
Hey @mfitch! 

It seems your source server installation is the source of your issues. Would you happen to have the full stack trace? It appears at first glance to be something that might happen if Grabbit failed to initialize properly. Are all bundles active? Does a direct request for content serve the same error? e.g  **xjzxdea0400x.dta.kp.org:4502/grabbit/content?path=/content/some-test-content**

**Comment by mfitch** [comment]
Full stack:

03.01.2017 10:44:42.794 *ERROR* [10.8.131.239 [1483469082784] GET /grabbit/content HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable
java.lang.UnsupportedOperationException: Deserialization not allowed for class org.springframework.batch.core.JobExecution (on Tue Jan 03 10:44:42 PST 2017)
  at org.kantega.notsoserial.DefaultNotSoSerial.preventDeserialization(DefaultNotSoSerial.java:256)
  at org.kantega.notsoserial.DefaultNotSoSerial.onBeforeResolveClass(DefaultNotSoSerial.java:248)
  at org.kantega.notsoserial.ObjectInputStreamClassVisitor.onBeforeResolveClass(ObjectInputStreamClassVisitor.java:48)
  at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
  at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
  at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
  at org.springframework.batch.support.SerializationUtils.deserialize(SerializationUtils.java:68)
  at org.springframework.batch.core.repository.dao.MapJobExecutionDao.copy(MapJobExecutionDao.java:50)
  at org.springframework.batch.core.repository.dao.MapJobExecutionDao.saveJobExecution(MapJobExecutionDao.java:60)
  at org.springframework.batch.core.repository.support.SimpleJobRepository.createJobExecution(SimpleJobRepository.java:145)
  at sun.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
  at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
  at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
  at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
  at org.springframework.batch.core.repository.support.AbstractJobRepositoryFactoryBean$1.invoke(AbstractJobRepositoryFactoryBean.java:172)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
  at com.sun.proxy.$Proxy31.createJobExecution(Unknown Source)
  at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:124)
  at com.twcable.grabbit.server.batch.ServerBatchJob.run(ServerBatchJob.groovy:47)
  at com.twcable.grabbit.server.services.impl.DefaultServerService$_getContentForRootPath_closure1.doCall(DefaultServerService.groovy:87)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
  at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
  at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
  at groovy.lang.Closure.call(Closure.java:423)
  at groovy.lang.Closure.call(Closure.java:439)
  at com.twcable.grabbit.jcr.JcrUtil.withSession(JcrUtil.groovy:80)
  at com.twcable.grabbit.server.services.impl.DefaultServerService.getContentForRootPath(DefaultServerService.groovy:64)
  at com.twcable.grabbit.server.GrabbitContentPullServlet.doGet(GrabbitContentPullServlet.groovy:86)
  at org.apache.sling.api.servlets.SlingSafeMethodsServlet.mayService(SlingSafeMethodsServlet.java:269)
  at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:345)
  at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:376)
  at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:546)
  at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:44)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77)
  at com.day.cq.wcm.core.impl.WCMDebugFilter.doFilter(WCMDebugFilter.java:156)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at com.day.cq.wcm.core.impl.WCMComponentFilter.filterRootInclude(WCMComponentFilter.java:362)
  at com.day.cq.wcm.core.impl.WCMComponentFilter.doFilter(WCMComponentFilter.java:177)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at com.day.cq.personalization.impl.TargetComponentFilter.doFilter(TargetComponentFilter.java:96)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at org.apache.sling.engine.impl.SlingRequestProcessorImpl.processComponent(SlingRequestProcessorImpl.java:282)
  at org.apache.sling.engine.impl.filter.RequestSlingFilterChain.render(RequestSlingFilterChain.java:49)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77)
  at com.adobe.cq.social.ugcbase.security.impl.SaferSlingPostServlet.doFilter(SaferSlingPostServlet.java:114)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at com.day.cq.dam.core.impl.assetlinkshare.AdhocAssetShareAuthHandler.doFilter(AdhocAssetShareAuthHandler.java:389)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at com.day.cq.dam.core.impl.servlet.ActivityRecordHandler.doFilter(ActivityRecordHandler.java:155)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:73)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:73)
  at com.adobe.granite.requests.logging.impl.RequestLoggerImpl.doFilter(RequestLoggerImpl.java:114)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at com.adobe.granite.csrf.impl.CSRFFilter.doFilter(CSRFFilter.java:220)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at org.apache.sling.security.impl.ContentDispositionFilter.doFilter(ContentDispositionFilter.java:181)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at com.day.cq.wcm.core.impl.AuthoringUIModeServiceImpl.doFilter(AuthoringUIModeServiceImpl.java:367)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at com.day.cq.wcm.core.impl.warp.TimeWarpFilter.doFilter(TimeWarpFilter.java:106)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at com.day.cq.wcm.mobile.core.impl.redirect.RedirectFilter.doFilter(RedirectFilter.java:248)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at org.kp.web.envconfig.core.filters.LoggingFilter.doFilter(LoggingFilter.java:50)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at org.apache.sling.engine.impl.debug.RequestProgressTrackerLogFilter.doFilter(RequestProgressTrackerLogFilter.java:95)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at com.day.cq.analytics.provisioning.impl.UserAuthenticationRequestFilter.doFilter(UserAuthenticationRequestFilter.java:119)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at com.adobe.cq.social.commons.cors.CORSAuthenticationFilter.doFilter(CORSAuthenticationFilter.java:91)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at com.day.cq.wcm.foundation.forms.impl.FormsHandlingServlet.doFilter(FormsHandlingServlet.java:285)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at com.adobe.granite.optout.impl.OptOutFilter.doFilter(OptOutFilter.java:74)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at com.adobe.cq.history.impl.HistoryRequestFilter.doFilter(HistoryRequestFilter.java:107)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at com.day.cq.wcm.core.impl.WCMRequestFilter.doFilter(WCMRequestFilter.java:90)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at com.adobe.cq.mcm.campaign.servlets.CampaignCopyTracker.doFilter(CampaignCopyTracker.java:100)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at org.apache.sling.rewriter.impl.RewriterFilter.doFilter(RewriterFilter.java:83)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at com.adobe.granite.httpcache.impl.InnerCacheFilter.doFilter(InnerCacheFilter.java:77)
  at com.adobe.granite.httpcache.impl.InnerCacheFilter.doFilter(InnerCacheFilter.java:56)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:129)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at com.adobe.granite.rest.impl.servlet.ApiResourceFilter.doFilter(ApiResourceFilter.java:68)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at org.apache.sling.bgservlets.impl.BackgroundServletStarterFilter.doFilter(BackgroundServletStarterFilter.java:169)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at com.adobe.granite.resourceresolverhelper.impl.ResourceResolverHelperImpl.doFilter(ResourceResolverHelperImpl.java:84)
  at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
  at org.apache.sling.engine.impl.SlingRequestProcessorImpl.doProcessRequest(SlingRequestProcessorImpl.java:151)
  at org.apache.sling.engine.impl.SlingMainServlet.service(SlingMainServlet.java:216)
  at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:85)
  at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:79)
  at org.apache.sling.security.impl.ReferrerFilter.doFilter(ReferrerFilter.java:290)
  at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
  at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
  at com.adobe.granite.license.impl.LicenseCheckFilter.doFilter(LicenseCheckFilter.java:308)
  at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
  at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
  at org.apache.felix.http.sslfilter.internal.SslFilter.doFilter(SslFilter.java:89)
  at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
  at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
  at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:129)
  at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
  at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
  at org.apache.sling.featureflags.impl.FeatureManager.doFilter(FeatureManager.java:116)
  at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
  at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
  at org.apache.sling.engine.impl.log.RequestLoggerFilter.doFilter(RequestLoggerFilter.java:75)
  at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
  at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
  at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:124)
  at org.apache.felix.http.base.internal.DispatcherServlet.service(DispatcherServlet.java:61)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
  at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
  at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
  at org.eclipse.jetty.server.Server.handle(Server.java:499)
  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
  at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
  at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
  at java.lang.Thread.run(Thread.java:745)

**Comment by jbornemann** [comment]
I wasn't able to produce this with a vanilla 6.2 (SP1) -> 6.2 (SP1). Is it possible that your notsoserial agent is still being started from agentlib on the command line per cq-ALL-hotfix-NPR-8364 (on receiving server)? This agent is automatically loaded now with SP1. Is it possible you have non-standard configuration in "Deserialization Firewall Configuration" or an old command line config that might be blocking deserialization of JobExecution?

I remember @viveksachdeva seeing this during discussion of unrelated #65

**Comment by viveksachdeva** [comment]
Yeah I remember seeing a similar issue.. I will give this one a try again and see if I can reproduce this...

**Comment by jbornemann** [comment]
Any luck @mfitch ?

**Comment by viveksachdeva** [comment]
I can reproduce this issue with Vanilla 6.2 -> 6.1 author

**Comment by mfitch** [comment]
The issue is resolved with:
removing these two from blacklist:
org.springframework.beans.factory.ObjectFactory
org.springframework.core.SerializableTypeWrapper$MethodInvokeTypeProvider
adding to whitelist:
org.springframework.
in OSGI


(I think the deserial fw is activated in SP1, raising the issue)
Thanks for your help!

**Comment by viveksachdeva** [comment]
@mfitch : Yeah that did fix the issue... @jbornemann : do you think we should add configuration for this..

**Comment by jbornemann** [comment]
@viveksachdeva yeah, I think we should provide a configuration for users to install, and link from the install page with description of what we are changing. I don't think it should be automatic. We don't want to clobber any existing project-specific security configuration. 

I've got one built. I'll update the README here shortly.
