### ISSUE TITLE
Grabbit Support for 6.5.5

### ISSUE THREAD

**Issue by sudarshanbisht** [TWCable/grabbit#237]
Thanks for taking the time to fill out an issue! To help the community solve your issue, please provide answers to the following questions, along with supporting log and configuration files.

We are using AEM 6.5.5 & want to sync content using the Grabbit between environments.  

**What version of AEM are you running?**
6.5.5

**How do you produce the issue?**
We installed Grabbit 7.1.5 but we are not able to sync the content between multiple author instances.

**Does the issue occur consistently?** 
Yes

**Any additional details?**
Log errors
`07.09.2020 11:30:07.835 *ERROR* [10.201.1.216 [1599492607829] GET /grabbit/content HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable
java.lang.IllegalArgumentException: Could not deserialize object
        at org.springframework.batch.support.SerializationUtils.deserialize(SerializationUtils.java:74)
        at org.springframework.batch.core.repository.dao.MapJobExecutionDao.copy(MapJobExecutionDao.java:50)
        at org.springframework.batch.core.repository.dao.MapJobExecutionDao.saveJobExecution(MapJobExecutionDao.java:60)

......................
Caused by: java.io.InvalidClassException: filter status: REJECTED
        at java.base/java.io.ObjectInputStream.filterCheck(ObjectInputStream.java:1343)
        at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1975)
        at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1851)`

**Comment by srikrishnasai** [comment]
Hi @sudarshanbisht ,
Can you please help me in getting the following packages that needs to be installed as the links present in repo were outdated.
1. Sun-Misc-Fragment-Bundle-1.0.0
2. Grabbit-Apache-Sling-Login-Whitelist-1.0
3. Grabbit-Deserialization-Firewall-Configuration-1.0
4. Grabbit-7.1.5

Thanks,
Krishna (ksai@ginnovat.com)

**Comment by srikrishnasai** [comment]
Hi @Shashi-Bhushan @sagarsane 
Can you please help me in getting the following packages that needs to be installed as the links present in repo were outdated.
1. Sun-Misc-Fragment-Bundle-1.0.0
2. Grabbit-Apache-Sling-Login-Whitelist-1.0
3. Grabbit-Deserialization-Firewall-Configuration-1.0
4. Grabbit-7.1.5

Thanks,
Krishna (ksai@ginnovat.com)

**Comment by subhak1086** [comment]
> 

Hi @srikrishnasai ,
Did you get the packages you requested above? I am looking to migrate content between AEM 6.5 environments. Any help is appreciated!

Thank You,
Subha K

**Comment by rohangargeq** [comment]
Hi @sudarshanbisht,
Were you able to find a fix for this problem ?

Thanks,
Rohan Garg
