### ISSUE TITLE
Nodes failing with NPE or IllegalStateException

### ISSUE THREAD

**Issue by jbyrnessnip** [TWCable/grabbit#43]
Nodes are failing with a NullPointerException or IllegalStateException on latest 6.1 branch recently merged with master.

Example node (author) on DWH server:
/content/dam/residential/specials-ola

Start of stack trace for NPE:
16.07.2015 18:16:17.044 *ERROR* [clientJobLauncherTaskExecutor-1] org.springframework.batch.core.step.AbstractStep Encountered an error executing step clientWorkflowOff in job clientJob
java.lang.NullPointerException: null
        at com.twcable.grabbit.client.batch.workflows.impl.DefaultWorkFlowManager.processConfig(DefaultWorkFlowManager.groovy:122)
        at com.twcable.grabbit.client.batch.workflows.impl.DefaultWorkFlowManager.access$0(DefaultWorkFlowManager.groovy)
        at com.twcable.grabbit.client.batch.workflows.impl.DefaultWorkFlowManager$_turnOff_closure1.doCall(DefaultWorkFlowManager.groovy:77)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)

Stacktrace for IllegalStateException:

16.07.2015 19:01:54.886 *ERROR* [clientJobLauncherTaskExecutor-3] org.springframework.batch.core.step.AbstractStep Encountered an error executing step clientWorkflowOn in job clientJob
java.lang.IllegalStateException: launcherConfig Map value for /etc/workflow/launcher/config/dam_xmp_writeback cannot be null
        at com.twcable.grabbit.client.batch.workflows.impl.DefaultWorkFlowManager$_turnOn_closure2.doCall(DefaultWorkFlowManager.groovy:94)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:439)

**Comment by jbyrnessnip** [comment]
Was not able to reproduce with latest 6.1 build.
