### ISSUE TITLE
InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag

### ISSUE THREAD

**Issue by frankglandorf** [TWCable/grabbit#77]
Using grabbit 4.0.x to copy from AEM 6.0 SP2 TO AEM 6.1 and get exception.

25.09.2015 14:27:39.690 *WARN* [0:0:0:0:0:0:0:1 [1443205659675] PUT /grabbit/job HTTP/1.1] com.twcable.grabbit.resources.GrabbitResourceProvider Unable to find resource for path: /grabbit.
25.09.2015 14:27:39.816 *INFO* [0:0:0:0:0:0:0:1 [1443205659675] PUT /grabbit/job HTTP/1.1] org.springframework.batch.core.launch.support.SimpleJobOperator Checking status of job with name=clientJob
25.09.2015 14:27:39.817 *INFO* [0:0:0:0:0:0:0:1 [1443205659675] PUT /grabbit/job HTTP/1.1] org.springframework.batch.core.launch.support.SimpleJobOperator Attempting to launch job with name=clientJob and parameters=timestamp=1443205659801,path=/content/nkuhome,host=devcms.nku.edu,port=80,clientUsername=admin,serverUsername=admin,serverPassword=admin,excludePaths=,workflowConfigIds=,deleteBeforeWrite=false
25.09.2015 14:27:39.974 *INFO* [0:0:0:0:0:0:0:1 [1443205659675] PUT /grabbit/job HTTP/1.1] org.springframework.batch.core.launch.support.SimpleJobOperator Checking status of job with name=clientJob
25.09.2015 14:27:39.974 *INFO* [clientJobLauncherTaskExecutor-1] org.springframework.batch.core.launch.support.SimpleJobLauncher Job: [FlowJob: [name=clientJob]] launched with the following parameters: [{serverPassword=admin, deleteBeforeWrite=false, port=80, clientUsername=admin, excludePaths=, workflowConfigIds=, timestamp=1443205659801, serverUsername=admin, host=devcms.nku.edu, path=/content/nkuhome}]
25.09.2015 14:27:39.990 *INFO* [0:0:0:0:0:0:0:1 [1443205659675] PUT /grabbit/job HTTP/1.1] org.springframework.batch.core.launch.support.SimpleJobOperator Attempting to launch job with name=clientJob and parameters=timestamp=1443205659974,path=/content/dam/nkuhome,host=devcms.nku.edu,port=80,clientUsername=admin,serverUsername=admin,serverPassword=admin,excludePaths=,workflowConfigIds=/etc/workflow/launcher/config/update_asset_mod|/etc/workflow/launcher/config/update_asset_create|/etc/workflow/launcher/config/dam_xmp_nested_writeback|/etc/workflow/launcher/config/dam_xmp_writeback,deleteBeforeWrite=false
25.09.2015 14:27:40.021 *INFO* [0:0:0:0:0:0:0:1 [1443205659675] PUT /grabbit/job HTTP/1.1] com.twcable.grabbit.servlets.GrabbitServlet Jobs started : [2300428396170152205, 6951605061390204383]
25.09.2015 14:27:40.037 *INFO* [clientJobLauncherTaskExecutor-2] org.springframework.batch.core.launch.support.SimpleJobLauncher Job: [FlowJob: [name=clientJob]] launched with the following parameters: [{serverPassword=admin, deleteBeforeWrite=false, port=80, clientUsername=admin, excludePaths=, workflowConfigIds=/etc/workflow/launcher/config/update_asset_mod|/etc/workflow/launcher/config/update_asset_create|/etc/workflow/launcher/config/dam_xmp_nested_writeback|/etc/workflow/launcher/config/dam_xmp_writeback, timestamp=1443205659974, serverUsername=admin, host=devcms.nku.edu, path=/content/dam/nkuhome}]
25.09.2015 14:27:40.995 *INFO* [clientJobLauncherTaskExecutor-2] org.springframework.batch.core.job.SimpleStepHandler Executing step: [clientWorkflowOff]
25.09.2015 14:27:41.151 *INFO* [clientJobLauncherTaskExecutor-2] org.springframework.batch.core.job.SimpleStepHandler Executing step: [clientNamespaceSync]
25.09.2015 14:27:41.198 *INFO* [clientJobLauncherTaskExecutor-1] org.springframework.batch.core.job.SimpleStepHandler Executing step: [clientWorkflowOff]
25.09.2015 14:27:41.198 *ERROR* [clientJobLauncherTaskExecutor-2] org.springframework.batch.core.step.AbstractStep Encountered an error executing step clientNamespaceSync in job clientJob
com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
	at com.google.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:73)
	at com.google.protobuf.CodedInputStream.checkLastTagWas(CodedInputStream.java:124)
	at com.google.protobuf.AbstractMessageLite$Builder.mergeFrom(AbstractMessageLite.java:213)
	at com.google.protobuf.AbstractMessage$Builder.mergeFrom(AbstractMessage.java:746)
	at com.google.protobuf.AbstractMessage$Builder.mergeFrom(AbstractMessage.java:238)
	at com.google.protobuf.AbstractMessageLite$Builder.mergeDelimitedFrom(AbstractMessageLite.java:282)
	at com.google.protobuf.AbstractMessage$Builder.mergeDelimitedFrom(AbstractMessage.java:760)
	at com.google.protobuf.AbstractMessageLite$Builder.mergeDelimitedFrom(AbstractMessageLite.java:288)
	at com.google.protobuf.AbstractMessage$Builder.mergeDelimitedFrom(AbstractMessage.java:752)
	at com.twcable.grabbit.proto.NamespaceProtos$Namespaces.parseDelimitedFrom(NamespaceProtos.java:149)
	at com.twcable.grabbit.client.batch.steps.namespace.NamespaceSyncTasklet.execute(NamespaceSyncTasklet.groovy:55)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:395)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:131)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:267)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:77)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:253)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:195)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:141)
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:64)
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:60)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:151)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:130)
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:135)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:301)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by jbornemann** [comment]
Does this reproduce?

**Comment by frankglandorf** [comment]
Happens every time I run the command:

curl -v -X PUT -H "Content-Type: application/json" -d "@devcms.json" -u
admin:admin http://localhost:4502/grabbit/job

**Comment by sagarsane** [comment]
Hi @frankglandorf , can you make sure that Grabbit was successfully installed on the `AEM 6 SP2` instance?

You can check by going to `/grabbit/job/all.json` on the Grabbit server, which would be AEM6 in this case. If Grabbit is successfully installed, you should get a blank JSON array ( `[]` ).

And in general, this issue is related to #30 .

**Comment by frankglandorf** [comment]
Installed grabbit on the aem 6 sp2 instance. GET of
http://devcms.nku.edu/grabbit/job/all produces:
HTTP ERROR: 503

Problem accessing /grabbit/job/all. Reason:

    AuthenticationSupport service missing. Cannot authenticate request.
Powered by Jetty://

**Comment by sagarsane** [comment]
Oh you have `v4.x.x` installed for AEM6.0 as well. As mentioned in the README, `v4.x.x` is compatible with AEM6.1; for AEM6.0, you should install `v3.x.x`. 

Can you try that and see if you still get the same issue?
You can find the releases on Bintray : https://bintray.com/twcable/aem/Grabbit#files

**Comment by frankglandorf** [comment]
Actually the README doesn't mention 6.0 specifically.

v4.0.x - AEM 6.1
v3.0.0 - CQ 5.6
v2.0.1 - CQ 5.6
v2.0.0 - CQ 5.6

All GET requests now return 503. Any suggestions for which bundles to
restart to restore the system?

**Comment by sagarsane** [comment]
Hey @frankglandorf I did some investigation over the weekend to see how you can restore the system form here. 

You can restore the system but you will have to directly replace 3 bundles from the OSGi Felix installation from another AEM6.0 SP2 instance.

The bundles are : 

```
bundle99 : Jackrabbit JCR Commons (org.apache.jackrabbit.jackrabbit-jcr-commons)
bundle108 : Apache Sling JCR Resource Resolver (org.apache.sling.jcr.resource)
bundle184 : Apache Sling API (org.apache.sling.api)
```

The bundle numbers should be the same for you as well since these are OOTB bundles.

You can find these bundles in `/crx-quickstart/launchpad/felix` 

So to get your system back, you can just shut down your instance, replace the above bundle folders with the ones from another 6.0 w/ SP2 instance and start the instance.

**Comment by jbornemann** [comment]
Hi @frankglandorf ! I hope we were able to help in some way! We are going to go ahead and close out this ticket as apart of some issue backlog housecleaning today! If you have further questions, or issues; feel free to reopen this ticket, or create another
