### ISSUE TITLE
ConstraintViolationException

### ISSUE THREAD

**Issue by jbornemann** [TWCable/grabbit#96]
Occasionally getting ConstraintViolationExceptions.  Known to happen for DAM paths, but may happen elsewhere too:

```
7.12.2015 09:11:57.498 *ERROR* [clientJobLauncherTaskExecutor-9] com.twcable.grabbit.client.batch.steps.jcrnodes.JcrNodesWriter Exception writing JCR Nodes to current JCR Session : session-1604903.
javax.jcr.nodetype.ConstraintViolationException: No matching property definition: jcr:lastModifiedBy = v575053
        at org.apache.jackrabbit.oak.jcr.delegate.NodeDelegate.setProperty(NodeDelegate.java:522)
        at org.apache.jackrabbit.oak.jcr.session.NodeImpl$35.perform(NodeImpl.java:1335)
        at org.apache.jackrabbit.oak.jcr.session.NodeImpl$35.perform(NodeImpl.java:1324)
        at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.perform(SessionDelegate.java:216)
        at org.apache.jackrabbit.oak.jcr.session.ItemImpl.perform(ItemImpl.java:113)
        at org.apache.jackrabbit.oak.jcr.session.NodeImpl.internalSetProperty(NodeImpl.java:1324)
        at org.apache.jackrabbit.oak.jcr.session.NodeImpl.setProperty(NodeImpl.java:360)
        at com.twcable.grabbit.jcr.ProtoPropertyDecorator.writeToNode(ProtoPropertyDecorator.groovy:54)
        at com.twcable.grabbit.jcr.ProtoNodeDecorator$_writeToJcr_closure5.doCall(ProtoNodeDecorator.groovy:72)
        at com.twcable.grabbit.jcr.ProtoNodeDecorator$_writeToJcr_closure5.call(ProtoNodeDecorator.groovy)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1379)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1372)
        at com.twcable.grabbit.jcr.ProtoNodeDecorator.writeToJcr(ProtoNodeDecorator.groovy:72)

```

**Comment by jdigger** [comment]
Suspect that this is related to enforcing protected fields (specifically foreign-key enforcement in this case) related to GH-65.
